
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:MusicR8r.Services.Providers.AlbumService.#ctor(MusicR8r.Data.Repositories.IEfRepository{MusicR8r.Data.Model.Models.Album},MusicR8r.Data.SaveContext.ISaveContext,MusicR8r.Services.Providers.IDateTimeProvider)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:MusicR8r.Services.GenreService.#ctor(MusicR8r.Data.Repositories.IEfRepository{MusicR8r.Data.Model.Models.Genre},MusicR8r.Data.SaveContext.ISaveContext,MusicR8r.Services.Providers.IDateTimeProvider)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:MusicR8r.Services.AlbumService.#ctor(MusicR8r.Data.Repositories.IEfRepository{MusicR8r.Data.Model.Models.Album},MusicR8r.Data.SaveContext.ISaveContext,MusicR8r.Services.Providers.IDateTimeProvider)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:MusicR8r.Services.ArtistService.#ctor(MusicR8r.Data.Repositories.IEfRepository{MusicR8r.Data.Model.Models.Artist},MusicR8r.Data.SaveContext.ISaveContext,MusicR8r.Services.Providers.IDateTimeProvider,MusicR8r.Services.Providers.IAlbumService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:MusicR8r.Services.SongService.#ctor(MusicR8r.Data.Repositories.IEfRepository{MusicR8r.Data.Model.Models.Song},MusicR8r.Data.SaveContext.ISaveContext,MusicR8r.Services.Providers.IDateTimeProvider)")]